import React from 'react'

const Posts = () => {
  return (
    <>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    <div>posts</div>
    </>
  )
}

export default Posts
